import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { slugData } from "./api/dummydata";

export default function Home() {
  const slugDatas = slugData.filter((x) => x.name === "home"); 

  return (
    <>
      <Head>
        <title>Home | BWI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="content bg_home"><div className="inner-content ">
          
            {/* <h1>Blue Willow Imagery</h1> */}
           
        </div>
        <aside className="inner-content">
          <div className="column">
            <ul>What we offer:
              <li>Glamour Shots</li>
              <li>Pin Up</li>
              <li>Boudoir</li>
              <li>Alt - Have something else in mind?</li>
            </ul>
            <p>"Showing women just how utterly strikingly beautiful inside and out they really are always gets to me…." - Bobbie</p>
          </div>
        </aside>  
      </section> 
    </>
  );
}
