import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { slugData } from "../api/dummydata";

export default function Home() {
  const slugDatas = slugData.filter((x) => x.name === "home"); 

  return (
    <>
      <Head>
        <title>Services | BWI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="content ">
        <div className="inner-content ">
          <div className="column bg_home">
            {/* <h1>Blue Willow Imagery</h1> */}
          </div>

       
        <aside className="column">
         {slugData[0]?.images.map((x) => (  <div className="inner-content"> 

          <div className="imageWrapper"><Image src={x.image} height={225} width={275} alt={"Photo example from a boudoir shoot"} /></div><Link href={`services/${x.link}`}><p>{x?.blurb}</p>
          </Link>

          </div>  ))}        
          
        </aside>        
        </div>
   </section> 
    </>
  );
}
