import Head from "next/head";
import  {faqs}  from "../api/dummydata";
import { useState } from "react";

export default function Faqs() { 
  const [isShowing, setIsShowing] = useState(false);

  const toggle = () => {
    setIsShowing(!isShowing);
  };



  return (
    <>s
      <Head>
        <title>FAQS | BWI </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        ></link>
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
      <header className="header set_bg" style={{backgroundImage: `url(${faqs[0]?.image})`}}>
        <div>
          <h1>FAQs</h1>
          </div>
        </header>
      <section className="content">  
      
        <div className="faq-content ">
        {faqs[0]?.questions.map((x) => ( <div className="row">
          <button className="accordion" onClick={toggle}><h3>{x.question}</h3>&#x2193;</button>
          <div
        style={{ display: isShowing ? "block" : "none", padding: "5px" }}
      
      ><p>{x.answer}</p></div>
        </div>
       ))}</div> 
      </section>
     
   
      
    </>
  );
}
