import Head from "next/head";
import { useRouter } from "next/router";
import { slugData } from "../../api/dummydata";
import Image from "next/image";
import Link from "next/link";

export default function Service() {
  const router = useRouter()
  const slugs = router.asPath.split('/')
  const slug = slugs?.pop().replace("/", "").replace("%20", " ").replace("-", " ")
  const slugDatas = slugData.filter((x) => x.name === slug); 
  const notServices = slug == 'about me' ? true : false
  return (
    <>
      <Head>
        <title>{slug} | BWI </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        ></link>
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
      <header className="header set_bg" style={{backgroundImage: `url(${slugDatas[0]?.image})`}}>
        <div>
          <h1>{slugDatas[0]?.name}</h1></div>
        </header>
      <section>    
        {/* <div className="content">
      <h2>{slug} {!notServices ? <span>sessions</span>: null}</h2>
        </div> */}
      </section>
     
        <aside className="content">
         {slugDatas[0]?.images.map((x) => (  <div className="inner-content">  
          <div className="imageWrapper"><Image src={x.image} height={225} width={275} alt={"Photo example from a boudoir shoot"} /></div><p>{x?.blurb}</p>
          
          </div>))}         
        </aside>
      
    </>
  );
}
