import Head from "next/head";
import { useRouter } from "next/router";
import { about_us } from "../api/dummydata";
import Image from "next/image";
import Link from "next/link";

export default function Service() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>{about_us.name} | BWI </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        ></link>
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
      <header className="header set_bg" style={{backgroundImage: `url(${about_us[0]?.image})`}}>
        <div>
          <h1>about us</h1></div>
        </header>
      <section>    
        <div className="content">
          <h2>Blue Willow Imagery</h2>
          <h3>Meet Bobbie</h3>
          <div className="about-inner-content">
            <span><p>{about_us[0].details}</p>
            <p>{about_us[0].more_details1}</p>
            <p>{about_us[0].more_details2}</p></span>
            <div className="imageWrapper"><Image src={about_us[0].bobbie} alt={"Photo of Bobbie and family"}/></div></div>

        </div>
        <div className="content">
          <h2>Gilded Glamour</h2>
          <h3>Meet Achaisha</h3>
          
          <div className="about-inner-content">
          <span>
            <p><Link href={"https://www.gildedglamourtx.com"}><u>gildedglamourtx.com</u></Link></p>
            {/* <p><Link href={"https://www.gildedglamourtx.com"}><u>Visit Gilded Glamour</u></Link></p> */}
            <p>Hair and Makeup Services. Specializing in the glamorous looks of the golden era. Pinup and vintage hairstyling and makeup is her specialty with a twist of modern! </p>
            <p>She has a wide variety of styling skills from vintage, traditional and bridal to extreme themed styles. She also specializes in wig styling and can be commissioned to create a styled wig for a specific look to your theme.</p>
          </span>
          <div className="imageWrapper"><Image src={about_us[0].achaisha} alt={"Photo of Achaisha"}/></div></div>
        </div>
      </section>
     
      <aside className="content">
        
      </aside> 
       
      
    </>
  );
}
