import Head from "next/head";
import { useRouter } from "next/router";
import { cityData } from "../api/dummydata";
import Image from "next/image";

export default function service() {
  const router = useRouter()
  const city = router.asPath.replace("/", "").replace("%20", " ")
  const cityDataAsArray = Object.keys(cityData).map((key) => {
    const data = cityData[key];
    const item ={
      name: key,
      data: data,
    }
    return item;
  }); 
  const cityDisplayed = cityDataAsArray.filter((x) => x.name = city)
  console.log(cityDisplayed)
  console.log(cityDataAsArray)
  return (
    <>
      <Head>
        <title>Texas | {city}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        ></link>
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
      <section>
        <div className="content">
          
          <h1>{city}</h1> 
          <p>{cityDisplayed?.details}</p>
         <div className="inner-content"> <ul>Sights to see:
            <li>Place A</li>
            <li>Place B</li>
            <li>Place C</li>
            <li>Place D</li>
            </ul></div>
          {/* <Image
            alt="city landmark"
            src={data.}
            width={300}
            height={250}
            /> */}
        </div>
      </section>
      <aside className="content">
        <div className="inner-content">
          <h2>More details about this city</h2>
        </div>
      </aside>
    </>
  );
}
