import Head from "next/head";
import { useRouter } from "next/router";
import { cityData } from "../api/dummydata";
import Image from "next/image";

export default function Service() {
  const router = useRouter()
  const city = router.asPath.replace("/", "").replace("%20", " ").replace("-", " ")
  const cityDetails = cityData.filter((x) => x.name === city); 
 
  return (
    <>
      <Head>
        <title>Texas | {city}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        ></link>
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
      <header className="header set_bg" style={{backgroundImage: `url(${cityDetails[0]?.image})`}}>
        <div>
          <h1>{cityDetails[0]?.name}</h1></div>
        </header>
      <section>    
        <div className="content">
          <h2>Why we love <span>{city}</span></h2>
          {cityDetails[0]?.isCapital ? <p>Texas Capital!</p>: null}
          <p>{cityDetails[0]?.details}</p>    
        </div>
      </section>
      <aside className="content">
        <div className="inner-content">  
        <ul>Sights to see:
          {cityDetails[0]?.sights.map((x) => 
            <li key={x.name}>{x.name}</li>)}
            </ul>
        </div>          
        <h2>More details about this city</h2>
      </aside>
    </>
  );
}
