import Head from "next/head";
import vintageBG from "../../assets/vintage-BG.jpg"
export default function Service() {
  return (
    <>
      <Head>
        <title>Pricing | BWI </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        ></link>
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
      <header className="header set_bg" style={{backgroundImage: `url(${vintageBG})`}}>
        <div>
          <h1>Our Pricing</h1></div>
        </header>
    
        <aside className="content">
        <div className="pricing-inner-content">  
         <h1>Lifestyle/Branding</h1>
         <p>50% non-refundable deposit due upon booking.</p>
         <ul>
          <li>Come Photo Ready</li>
          <li>Studio</li>
          <li></li>
         </ul>

        </div>
        <div className="pricing-inner-content">  
         <h1>Collections</h1>
         <p>Full day shoots.</p>
         <ul>
          <li>$500 session fee</li>
          <li>Optional Hair/Makeup ($200 more)</li>
          <li></li>
         </ul>

        </div>
          
                
        </aside>
     
    </>
  );
}
