import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import Link from "next/link";
import AliceCarousel from "react-alice-carousel";
import vintageBG from "../../assets/vintage-BG.jpg"
import lifeStylePricing from "../../assets/pricing/Lifestyle Pricing.jpg"
import pricingGuide from "../../assets/pricing/Pricing Guide .jpg"
export default function Service() {
  return (
    <>
      <Head>
        <title>Pricing | BWI </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        ></link>
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
      <header className="header set_bg" style={{backgroundImage: `url(${vintageBG})`}}>
        <div>
          <h1>Our Pricing</h1></div>
        </header>
    
        <aside className="content">
        <div className="pricing-inner-content">  
          <Image src={lifeStylePricing} height={500
          } width={275} alt={"Photo example from a boudoir shoot"} />
            <Image src={pricingGuide} height={500
          } width={275} alt={"Photo example from a boudoir shoot"} /></div>
          
                
        </aside>
     
    </>
  );
}
