import Head from "next/head";
import { useRouter } from "next/router";
import { slugData } from "../../api/dummydata";
import Image from "next/image";
import Link from "next/link";
import AliceCarousel from "react-alice-carousel";
import ImageGallery from "react-image-gallery"


export default function Service() {
  const router = useRouter()
  const slugs = router.asPath.split('/')
  const slug = slugs?.pop().replace("/", "").replace("%20", " ").replace("-", " ")
  const slugDatas = slugData.filter((x) => x.name === slug); 

  const pictures =[ <div>{ slugDatas[0]?.images.map((x) => <img src={x.image} width={300} alt={""} role="presentation" />)}</div>]
  const responsive = {
    0: { items: 1 },
    568: { items: 2 },
    1024: { items: 3 },
    1480: { items: 4 }
  };
  return (
    <>
      <Head>
        <title>{slug} | BWI </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        ></link>
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
      <header className="header set_bg" style={{backgroundImage: `url(${slugDatas[0]?.image})`}}>
        <div>
          <h1>{slugDatas[0]?.name}</h1>
        </div>
      </header>
      <section className="content">
        {/* <AliceCarousel
           mouseTracking
           items={items}
           autoWidth={true}
           disableDotsControls={true}
           keyboardNavigation={true}
           responsive={responsive}
          
        /> */}
        <ImageGallery items={pictures} />
      </section>
    </>
  );
}
